### ISSUE TITLE
⚡ 一样的图标

### ISSUE THREAD

**Issue by linjunpop** [MartianZ/fakeThunder#1]
点击之后居然是分享，感觉表意不明。

**Comment by MartianZ** [comment]
在BT任务中会有“查看BT任务列表”功能
在影音任务中会有“云点播”功能

其他任务中目前就只有“分享”，这些功能还在开发，后续还会有“删除”等等。

图标的原因……因为自己实在是不会设计和绘图，所以就随便用了一个……

**Comment by linjunpop** [comment]
或者一个简单的向下的箭头就好？ :smile:

**Comment by MartianZ** [comment]
最初是用的向下的箭头来着，感觉不好看又换了这个……

UI的确是个问题呢，慢慢调整吧
