### ISSUE TITLE
登陆刷新后什么都没有显示

### ISSUE THREAD

**Issue by joyurock** [MartianZ/fakeThunder#100]
登陆刷新后什么都没有显示，任务也加载不了，新的任务添加后就直接崩溃了....怎么办？？？

**Comment by MartianZ** [comment]
现在好像是有一些问题，明天我再查查看。可能是迅雷那边有所更改吧

另外迅雷现在除了最新的Mac版本，支持离线功能，您可以尝试一下

**Comment by ccoossdddffdd** [comment]
迅雷更新了web接口  取离线任务列表的部分可以使用在线js接口的方式取了

不过相应的  旧的正则方式处理的部分就不能用了...

http://dynamic.cloud.vip.xunlei.com/interface/showtask_unfresh

**Comment by MartianZ** [comment]
@cosnis 求详细……

**Comment by ccoossdddffdd** [comment]
登录离线 直接访问下面的就能看到了

http://dynamic.cloud.vip.xunlei.com/interface/showtask_unfresh?callback=jsonp13660767159384&type_id=4&page=1&tasknum=30&p=1&interfrom=task

**Comment by binux** [comment]
https://github.com/binux/lixian.xunlei/commit/117b8b932f970d3081f430540691f4c29ab03f9b

我这边更新了，但是st=0不可用，st=4需要自行过滤已过期的任务

**Comment by ccoossdddffdd** [comment]
不过貌似后面播放的地方  也改了....    被302到一个 443端口的地方... 然后无下文....

**Comment by ccoossdddffdd** [comment]
@binux 播放的时候有问题么?  分享下解决办法吧~  ^_^

**Comment by binux** [comment]
@cosnis 

url = "http://vod.lixian.xunlei.com/share.html?"+$.param({
      from:'lxweb',
      url: task.find(".task-vod-url").attr("href"),
      filename: task.find(".task-title").text(),
      t: new Date(),
      gcid: (task.find(".task-vod-url").attr("href").match(/&g=(\w+)/)||"")[1],
      cid: (task.find(".task-vod-url").attr("href").match(/&i=(\w+)/)||"")[1],
      filesize: (task.find(".task-vod-url").attr("href").match(/&s=(\w+)/)||"")[1],
      isvip: 1,
  });

这个地址没问题

**Comment by ccoossdddffdd** [comment]
@binux 能用mplay之类的播放么?

**Comment by binux** [comment]
@cosnis 好久没弄了，不知道可不可以

**Comment by ccoossdddffdd** [comment]
@binux .... 以前是可以用 http://i.vod.xunlei.com/req_get_method_vod 拿到然后用 mplayer 播放没问题  现在拿到的就用不了了... T_T

**Comment by MartianZ** [comment]
@cosnis 不知道有没有别的办法取到可以用的实际的播放地址，加上Cookies如果可以的话就可以……具体再看看……

**Comment by ccoossdddffdd** [comment]
@MartianZ 以前的机制 不用加cookies也可以播放.....   我测试过的.... 现在的没试过加cookie  晚上再试试吧

**Comment by MartianZ** [comment]
@cosnis 我记得以前是必须加Cookies的

**Comment by ccoossdddffdd** [comment]
@MartianZ  = =!!   那就不知道是什么原因了... 我之前是得到 url 地址后直接在 mplayerX 里 open url 打开的  然后可以播放... 

 关注看你更新的结果吧~  嘿嘿~~

**Comment by joyurock** [comment]
@MartianZ 我还是等你的更新吧～我在国外...迅雷那个官方的离线在国外下载只有10k每秒...我都郁闷死了

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
迅雷官方的for Mac老是去不了满速。用FakeThunder去到1.2mb/s~1.4mb/s妥妥的，官方的只能保持在800kb/s左右。

**Comment by 98827ddb7e5a2c2e261912a23d9251d6** [comment]
期待更新~~~

**Comment by MartianZ** [comment]
问题已修复，新版本已经发布，请在软件中运行“检查更新”
