### ISSUE TITLE
列表无法刷新，添加任务意外退出

### ISSUE THREAD

**Issue by Nivekul** [MartianZ/fakeThunder#104]
RT
上次在刷新列表的时候添加了个任务然后就突然意外退出了，之后就一直处于这个无法刷新和添加任务的时候意外退出的情况了。。。。

**Comment by MartianZ** [comment]
版本号为？请运行检查更新升级到最新版

**Comment by Nivekul** [comment]
本来以为是版本问题，但是是最新版的，然后没办法我就去下了个官方的迅雷，但是发现点击到离线空间后也是出现意外退出的情况。。

**Comment by MartianZ** [comment]
你是在国外么？

版本是1.0(12)么？

**Comment by Nivekul** [comment]
是在国外，版本是1.0（11），我刚刚下了个还是这个版本诶。。不是12的

**Comment by MartianZ** [comment]
请在软件里面运行检查更新，更新到12版本即可解决问题

**Comment by Nivekul** [comment]
解决了，谢谢~
