### ISSUE TITLE
BT 文件夹重复

### ISSUE THREAD

**Issue by linjunpop** [MartianZ/fakeThunder#11]
一个 bt 的文件夹被创建了两层

如图：

![](http://f.cl.ly/items/0a080P3Q2d0B0p0b3s3Z/Screen%20Shot%202012-07-26%20at%2012.19.26%20PM.png)

**Comment by MartianZ** [comment]
这是因为本身bt种子中就多一个文件夹导致这个问题吧，不是很好判断呢。

**Comment by linjunpop** [comment]
@MartianZ 查看过了，种子并没有多文件夹。

不知道是个例还是 bug

**Comment by MartianZ** [comment]
看看种子的这个mkv的文件标题是不是 目录名\文件名.mkv 的格式
是的话就是多了一层目录，应该是个例，我这边没出现这种问题

**Comment by linjunpop** [comment]
@MartianZ http://imax.im/movies/600 11G 的那个

**Comment by MartianZ** [comment]
经过确认是BT种子本身多包含一层文件夹所致，不是软件问题。

**Comment by linjunpop** [comment]
@MartianZ 哦，不好意思，因为只在迅雷的 web 上查看，没发现有文件夹。
