### ISSUE TITLE
1.0(12)无法刷出下载列表

### ISSUE THREAD

**Issue by wio-xx** [MartianZ/fakeThunder#111]
无论如何彻底删除重装，注销登录，都不行。

**Comment by watson2006** [comment]
我的也一样

**Comment by hasumi** [comment]
无法刷新是已有任务当中有特殊字符，如分隔符' 。删除这个任务即可，尤其是电驴的原始地址含有这类字符，当你简单改名是无效的，除非连带原始的ed2k地址中字符也一并修改。
