### ISSUE TITLE
无法用迅雷帐号登录

### ISSUE THREAD

**Issue by woshow9** [MartianZ/fakeThunder#112]
登录失败，请检查您的用户名和密码！并确保当前的fakeThunder为最新版本。如果仍然无法正常登录，请到官方网站发送反馈。

1、密码是正确的，网页登录没有问题。
2、软件版本也是最新下载的。

**Comment by sianchan** [comment]
同样登录失败，无法下载。

**Comment by xqiushi** [comment]
我也有这个问题，亲 肿么办啊？

**Comment by xi3047** [comment]
我也登陆不了。账号和密码都没错能登陆官网的
