### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by xi3047** [MartianZ/fakeThunder#116]
无法登陆了，检查了是最新版本，用户名和密码在官网等登进去。求解决

**Comment by sd1650644** [comment]
显示登录失败，请检查您的用户名和密码！并确保当前fakethunder为最新版本。

**Comment by xi3047** [comment]
...说了已经检查过了是最新版本了。用户名密码都没错的

**Comment by sd1650644** [comment]
废话，当然是最新版本帐号密码都正确还是登不上才来问好吗

**Comment by chenhuiapp** [comment]
同样登录不上去...可能是验证码的问题吧...求解决！

**Comment by againpro** [comment]
同样的问题。软件版本 Version 1.0(12)  系统10.8   2011 Macbook Pro
