### ISSUE TITLE
有没有人啊  能不能解决一下啊 谢谢 帐号改了密码登不上去了

### ISSUE THREAD

**Issue by cherry223** [MartianZ/fakeThunder#119]
帐号改了密码登不上去了

**Comment by cherry223** [comment]
不只是旧的号码登不上去了 新买的帐号也登不上去

**Comment by hasumi** [comment]
设置-高级，清除hash和cookies，再次打开登录试试看

**Comment by cherry223** [comment]
点清除hash和cookies 没反应

**Comment by againpro** [comment]
同样的问题。软件版本 Version 1.0(12)  系统10.8   2011 Macbook Pro
