### ISSUE TITLE
fakethunder都不能登陆了啊！！！

### ISSUE THREAD

**Issue by intro2y** [MartianZ/fakeThunder#120]
前段时间没改密码，能登陆，但是列表刷新不了，后来改了次密码，现在都不能登录了，清楚过cookie和hash，也没用。

**Comment by againpro** [comment]
同样的问题。软件版本 Version 1.0(12)  系统10.8   2011 Macbook Pro

**Comment by shiniv** [comment]
估计是因为迅雷加了验证码了把
