### ISSUE TITLE
求助，软件无法登录。

### ISSUE THREAD

**Issue by againpro** [MartianZ/fakeThunder#121]
大约1个月前开始不能登录。软件版本 Version 1.0(12)  系统10.8   2011 Macbook Pro

**Comment by intro2y** [comment]
我的可能有2个多礼拜不能登陆，然后昨天又莫名其妙的好了~

**Comment by MartianZ** [comment]
现在登陆好像是出现了一些问题，因为最近放假回到家没有关注，我飞回去以后立刻抽空研究一下，抱歉影响各位使用了

2013/7/31 intro2y notifications@github.com

**Comment by qqldd** [comment]
同样无法登录，显示：登录失败，请检查您的用户名和密码！并确保当前的fakeThunder为最新版本。如果仍然无法正常登录，请到官方网站发送反馈。

但是在lixian.xunlei.com可以登录
