### ISSUE TITLE
当资源含有 ' 这字符的时候会无法刷新list，添加该类资源会直接崩溃

### ISSUE THREAD

**Issue by hasumi** [MartianZ/fakeThunder#123]
如题。当资源含有 ' 这字符的时候会无法刷新list，添加该类资源会直接崩溃。

无法刷新是已有任务当中有特殊字符，如分隔符' 。删除这个任务即可。
尤其是电驴的原始地址含有这类字符，当你简单改名是无效的，除非连带原始的ed2k地址中字符也一并修改。

**Comment by MartianZ** [comment]
新版fakeThunder会解决这个问题，感谢反馈
