### ISSUE TITLE
Issue: Please update the package on your server

### ISSUE THREAD

**Issue by cnbeining** [MartianZ/fakeThunder#126]
Hi,

I am experiencing the difficulty of cannot login with fakeThunder on OSX 10.9, python 2.7.6. When I try to do everything under command line, I got this error:

wifihost-83-141:~ ########$ /Applications/fakeThunder.app/Contents/MacOS/fakeThunder ; exit;
-e:1:in `<main>': undefined method`each' for "":String (NoMethodError)
  File "/Applications/fakeThunder.app/Contents/Resources/XunleiAPI/api_mini.py", line 35
    print 'USER LOGIN SUCCESS: ' + username
                               ^
SyntaxError: invalid syntax

Maybe it 's the problem with the version of my python, but it didn't work on python 3.3.2.

I've noticed some of your recent commits on this repo here, while the installer on your server was built around 7 months ago. Maybe building a new version can solve this issue?

Yours Sincerely,
Beining

**Comment by MartianZ** [comment]
Hi there,

Currently I'm re-designing fakeThunder and the Python API is discarded on the latest version on this repo, pretty sure your problem will be solved on next update.

I will release the new version when everything is ready. But now I'm suffering the new policy of App Signing on OS X 10.9 now and try to solve it.

**Comment by cnbeining** [comment]
Hi,

Thank you very much, and good luck with your work. 

BTW，thanks again for the aria2c you compilled. That really helps, especially for OSX 10.9, which is suffering from all kinds of problems with brew, port and make. Without your work, it would be nearly impossible for any user to install a aria2c by themselves.

Have a nice day, and happy halloween!

Yours,
Beining

**Comment by MartianZ** [comment]
@superwbd 
Hi,
fakeThunder 2.0.14 has been released! You can either run "Check for update" or download the latest version on http://martianz.cn/fakethunder/.

Hope you like the new version of fakeThunder :D

**Comment by cnbeining** [comment]
![image](https://f.cloud.github.com/assets/1560962/1513082/4bcd276e-4adb-11e3-8570-0535412c929e.png)

Besides of that, everything seems to be working properly...

Thank you very much for your work, I (as long as all of your users) would appreciate it with no doubt.

Yours,
Beining
