### ISSUE TITLE
添加资源的输入框可以改为无格式么

### ISSUE THREAD

**Issue by hasumi** [MartianZ/fakeThunder#128]
有时候拷贝链接会直接成为超链接格式，而无法被软件识别

**Comment by MartianZ** [comment]
超链接格式不会影响软件识别的，不过确实不太美观，后面会进行修复。

**Comment by hasumi** [comment]
可是有时候拷贝粘贴上的结果就是带链接的名字，而无法添加（比如电驴的链接）。另外有时候有些资源含有特别字符添加后造成空白文件名的情况，比如电驴链接中以unicode编码的&符号什么的，偶发。

**Comment by MartianZ** [comment]
带链接的名字说明你拷贝的不对啊。。如果拷贝的是正确的话有格式也是可以添加的

**Comment by hasumi** [comment]
明白，我使用clipmenu，从clipmenu中粘贴出来是正常的。
