### ISSUE TITLE
支持GateKeeper

### ISSUE THREAD

**Issue by venj** [MartianZ/fakeThunder#13]
能不能在你打包程序的时候用Developer ID签署一下，支持ML的Gate Keeper？

**Comment by MartianZ** [comment]
默认我是签署了，但是不知道为什么还是不行，也懒得再看苹果的文档，我的每款应用都发不上去MAS，伤心了。

**Comment by venj** [comment]
建议你看一下下面这个视频，里面有详细的使用Developer ID签名的方法：
https://developer.apple.com/videos/wwdc/2012/?id=702

简单的说，就是，在mac developer portal site里注册一下机器；然后在Organizer里，Device标签下，选中Library － Provisioning Profiles部分，使用菜单Editor － Refresh From Developer Portal；把新创建并导入的Mac Team Provisioning Profile拖到“My Mac”的Provisioning Profile下。

Archive程序的时候，选择Developer ID的那个数字签名，然后使用Developer ID方式Distribute。

**Comment by MartianZ** [comment]
1.0(5)版本修改了一下，应该签署成功了。您查看一下，看看还有没有问题
