### ISSUE TITLE
无法刷新列表，添加任务成功网页上能看见但列表未刷新

### ISSUE THREAD

**Issue by admk** [MartianZ/fakeThunder#130]
如上，删除掉的任务还出现在列表中，双击后任务消失，再次刷新任务瞬间出现，新添加的任务（不管是软件还是网页上添加）都没有显示。

添加任务成功但列表没有更新，网页上显示已添加。

如何重新登录重开删除配置都无效。怀疑是刷新键没有正确地下载文件列表而只从缓存中读取？

**Comment by MartianZ** [comment]
我最近也注意到了这个问题，只是偶尔会发生。

上次Debug没有找到原因，最后竟然修改了一下请求过程的User-Agent就修复了。

可能是缓存的问题，也可能是迅雷那边的问题，我会继续排查

感谢反馈

**Comment by admk** [comment]
刚刚删除了系统的缓存并重启fakethunder后就好了，目录为`/Users/{用户名}/Library/Caches/la.4321.fakeThunder`

**Comment by MartianZ** [comment]
嗯，这样啊。非常感谢，下个版本会修复这个问题
