### ISSUE TITLE
16位字母数字符号组成的复杂密码登录失败

### ISSUE THREAD

**Issue by CocoaBob** [MartianZ/fakeThunder#18]
不知道什么原因，我尝试用我真正的16位密码登录，直接提示失败。如果随便写一个短一点的密码，则是等会儿后再提示登录失败。

我还在看源码，暂时还没理清头绪，怎么是对127.0.0.1发送request呢…

**Comment by yyfearth** [comment]
貌似有特殊字符的就不行，我12位只有几个特殊字符也不行的

**Comment by CocoaBob** [comment]
仔细看了一下，应该是迅雷API里Python代码里某处的问题。不知道这些Python代码是不是迅雷官方提供的？
实在不了解Python程序怎么调试，怎么设断点……不知道该如何一步步调试……

**Comment by MartianZ** [comment]
@CocoaBob Python程序显然不是迅雷官方提供的，是修改自loli.lu项目
@yyfearth 应该是Python程序问题，这个问题有几个用户反馈了，我会注意的。

谢谢反馈喵～
