### ISSUE TITLE
增加“打开保存目录”、开始、暂停功能

### ISSUE THREAD

**Issue by lionhoho** [MartianZ/fakeThunder#20]
希望在开始本地下载旁边增加打开保存目录功能（按钮）
另外就是给单个任务添加开始、暂停功能（按钮）

再顶！

**Comment by MartianZ** [comment]
在任务显示速度的时候，单击按钮即可暂停任务

在任务显示下载完成的时候，单击按钮即可打开目录定位到文件

**Comment by MartianZ** [comment]
忘记说了

“在任务显示下载完成的时候，单击按钮即可打开目录定位到文件”

这个功能稍微有一些问题，刚在最新的代码中修复，下个版本的更新会解决问题
