### ISSUE TITLE
MPlayerX 无法拖动进度条

### ISSUE THREAD

**Issue by nutinshell** [MartianZ/fakeThunder#23]
一旦拖动便不再播放。

Mac 10.8 
MPlayer 1.0.14

**Comment by MartianZ** [comment]
快进的话需要自己处理流，比较麻烦，暂时不会支持。

**Comment by MartianZ** [comment]
如果需要频繁快进的话还是推荐直接到lixian.xunlei.com使用在线播放器

**Comment by nutinshell** [comment]
这个杯具，mp播放经常会意外退出。

**Comment by binux** [comment]
用libvlc写一个如何？

**Comment by MartianZ** [comment]
@binux -_,- 写不出来……
