### ISSUE TITLE
希望增加使用第三方下载器的选项

### ISSUE THREAD

**Issue by rommelgod** [MartianZ/fakeThunder#27]
比如说我想用speed download下载  点一下本地下载旁边的箭头就会出现使用speed download下载  这样的话软件就实用多了

**Comment by MartianZ** [comment]
或许会增加这个功能

但是speed download是肯定不可能的，因为这个不支持设置header或者cookie.

**Comment by rommelgod** [comment]
那可以复制下载连接  效果也是一样的   ps 神一般的回复速度啊  哈  我在macidea看见过你的

**Comment by MartianZ** [comment]
仅仅有下载连接没法下载，必须设置Cookie（http header）

**Comment by rommelgod** [comment]
哈  我不是那个意思啊   我是说如果像迅雷网页版离线下载那样   右击资源一下有一个复制下载连接  然后用户就可以在speed download 中用手动添加新任务的方式进行下载

**Comment by MartianZ** [comment]
额，那个地址好像不太一样，没仔细研究过……反正我这个地址还是得用Cookie才行……
