### ISSUE TITLE
希望增加aria2的JSON-RPC导出支持

### ISSUE THREAD

**Issue by miniers** [MartianZ/fakeThunder#30]
大神你好,能否支持下JSON-RPC的导出呢?
http://blog.binux.me/2012/07/thunderlixianexporter/
类似与这个脚本的功能.
这样就可以实现导出到NAS中进行脱机下载了 不用一直开着软件.
自己尝试着在你的源码基础上进行增加..无奈水平略低..呵呵
再次感谢MartianZ大神的付出..

**Comment by binux** [comment]
于是干嘛不干脆直接用http://binux.github.com/ThunderLixianExporter/

**Comment by miniers** [comment]
呵呵  想着用软件比开网页要方便嘛..嗯..给你添麻烦啦..谢谢哈..
那就继续用网页版把..Thanks
