### ISSUE TITLE
下载进度以及剩余所需下载时间，最后就是通知栏支持啦～

### ISSUE THREAD

**Issue by JimmyRespawn** [MartianZ/fakeThunder#32]
进度倒也无所谓，主要想知道剩余所需下载时间，给个大致的就行，老是看所需时间改变心也慌。
然后就是ML下载完成通知栏提示支持～
最后感谢下为我们带来如此强大的一款软件～

**Comment by MartianZ** [comment]
i'm working on this

thx for your advice :)
