### ISSUE TITLE
10.(7) 还是刷不出列表

### ISSUE THREAD

**Issue by fantasyx** [MartianZ/fakeThunder#35]
还有登录，有时候帐号密码是正确的，却说我错误，我是复制粘贴进去的，重启又好了 。
列表还是刷不出来， 10.8 ML
有时候把帐号贴入帐号，光标离开后，帐号栏又空了。
最主要还是先fix 列表吧，都一个星期不能用了哟。
thx

**Comment by fantasyx** [comment]
今天重新的登录了一下，又可以刷出列表了
加载更多不好用了。。。

**Comment by ipopo** [comment]
一样有刷不出列表的问题。

**Comment by fantasyx** [comment]
10（10） 全部问题解决！
