### ISSUE TITLE
BT种子下载方法（希望能放在项目首页以及pcbeta）

### ISSUE THREAD

**Issue by 29x10** [MartianZ/fakeThunder#36]
finder中cmd+c复制种子文件，到terminal中cmd+v,得到的完整路径复制下来
然后fakeThunder添加任务
输入file://然后cmd+v刚才的完整路径即可添加任务

**Comment by MartianZ** [comment]
谢谢

这个提供了一个更简单的方法添加任务

**Comment by 29x10** [comment]
想到一个更好的办法，在种子的下载目录，新建一个xia.sh文件
输入
`s="file://"${PWD%*}/$1`
`echo $s | pbcopy`
运行sh xia.sh 种子名，tab键自动补全种子名
然后路径就直接到你的剪贴板了

**Comment by 29x10** [comment]
发现还是不行，pbcopy会自带一个回车

**Comment by MartianZ** [comment]
嘛嘛，只要有文件的路径，通过NSURL可以很快转换成file://

我下个版本会直接添加BT种子文件支持的，谢谢
