### ISSUE TITLE
增加取消下载的功能

### ISSUE THREAD

**Issue by ruizzz** [MartianZ/fakeThunder#37]
误点中一个下载任务，浪费了我半小时……
希望可以增加取消单个下载任务\单个文件下载的功能，谢谢！

**Comment by MartianZ** [comment]
当按钮显示速度的时候，再次点击一下，就可以暂停任务了，这时候直接删除未下载完成的文件即可

**Comment by ruizzz** [comment]
好的，谢谢！

**Comment by ruizzz** [comment]
还是希望能增加一个“取消下载任务”的功能，这对于有很多文件的bt下载任务还是很有用了，一个文件一个文件的点真心很悲剧……

**Comment by MartianZ** [comment]
BT任务的取消的确没有考虑到……后续我会想办法添加的

**Comment by ruizzz** [comment]
好的，谢谢！
