### ISSUE TITLE
希望开发者能做好代码注释

### ISSUE THREAD

**Issue by tangpei1215** [MartianZ/fakeThunder#39]
希望开发者能做好代码注释，能让更多的开发者参与进来，做出更好的产品。

**Comment by MartianZ** [comment]
哪里的代码让你疑惑……

**Comment by tangpei1215** [comment]
具体的代码我还没有研究，我是想说开发的时候比较不好懂的地方请加好注释。谢谢。

**Comment by MartianZ** [comment]
@tangpei1215 我不觉得把注释写好就会有人帮忙开发

**Comment by tangpei1215** [comment]
好吧。。。

**Comment by limbo0312** [comment]
无语

**Comment by MartianZ** [comment]
@limbo0312 有什么无语的？

@tangpei1215 基本上每一个function我都有写是什么用途，整体思路我觉得是比较清晰，如果哪里有问题直接具体问，而不是直接说“能不能把注释都写好”，我也不会清除是哪里你不明白，有些我觉得一目了然的东西不见得你就会明白。

如果你没有耐心去看几行我的代码请不要来发代码上的issue。
