### ISSUE TITLE
登陆看起来是通过 thunder.4321.la 有安全隐患

### ISSUE THREAD

**Issue by huacnlee** [MartianZ/fakeThunder#4]

**Comment by MartianZ** [comment]
密码是两次MD5以后储存的，然后hash是session，哪里有安全隐患了？

**Comment by MartianZ** [comment]
虽然没有安全隐患，但是因为是统一处理的登录，结果被迅雷给禁止了。

最新的版本已经将所有的部分交给本地处理，不再存在任何安全隐患
