### ISSUE TITLE
启动fakeThunder时，系统原有python进程会被结束

### ISSUE THREAD

**Issue by rocdeng** [MartianZ/fakeThunder#42]
启动fakeThunder时，系统原有python进程会被结束，难道是使用了killall？
冲突软件：goagent（使用python proxy.py启动代理）
系统版本：MAC OS X 10.8

**Comment by lqik2004** [comment]
@rocdeng 看了下代码，在启动的过程中确实是使用了killall，为了运行Python写的那个xunlei.lixian的库
所以，只能改变个方式才能解决这个bug了
我倒是建议放弃使用那个Python的库，没什么必要，我可以提供一个纯ObjC写的迅雷离线API，基本功能完备。

**Comment by MartianZ** [comment]
@rocdeng @lqik2004 的确是用了killall，当时忽视了这个问题，加上简单的启动参数判断应该可以找到应该结束的Python，后续会修复

@lqik2004 纯Objc的迅雷API么？已经开发完成了么？我还在开发……不过我现在想着准备重构整个项目，准备仍然用Python，然后界面采用HTML做，下载采用JavaScript和aria2c通信做。

**Comment by lqik2004** [comment]
@MartianZ 基本上完成了，现在实现登陆，获取任务（包括名称，大小，类型等相关信息），BT任务列表，云转码任务列表，添加到云转码，云播放，添加任务（链接，上传BT种子没做），删除任务
如果有需要咱们可以联系

**Comment by MartianZ** [comment]
@lqik2004 嗯，确实需要。如果能够提供帮大忙了，我的GTalk：fzyadmin@gmail.com 或 QQ：6708539

**Comment by rocdeng** [comment]
太好了，强强联手啊！期待更新 :)

**Comment by messense** [comment]
其实只要每次启动 python api 进程的时候记录 进程 PID 到 UserDefaults 里面，以后打开软件的时候读取保存的 PID 看看进程还在不在运行，在运行就 kill 掉它呗。
