### ISSUE TITLE
使用MplayerX播放不能跳转到特定时间

### ISSUE THREAD

**Issue by lqik2004** [MartianZ/fakeThunder#44]
如题，
跳转之后就不能继续播放了，只能从头看

**Comment by ruizzz** [comment]
这其实是mplayerx的问题，我用mplayerx看内网NAS的视屏也这样，后来换movist了。

**Comment by lqik2004** [comment]
哦，多谢，我换一个试试看

发自我的 iPhone

在 2012-8-17，下午7:19，ranye notifications@github.com 写道：

这其实是mplayerx的问题，我用mplayerx看内网NAS的视屏也这样，后来换movist了。

—
Reply to this email directly or view it on
GitHubhttps://github.com/MartianZ/fakeThunder/issues/44#issuecomment-7815464.
