### ISSUE TITLE
fakeThunder下载中的不完整视屏文件在finder中显示时会导致一个quicklook进程占用大量的CPU

### ISSUE THREAD

**Issue by ruizzz** [MartianZ/fakeThunder#46]
电脑突然发热很厉害，用safari浏览网页都很卡，于是打开活动监视器看了下，发现一个叫QTKitServer-(XXXX)QuickLookSatellite-general的进程占用了大量的CPU，干掉了还会死而复生。上网搜了下应该是quicklook在为一个格式为quicktime支持、但不完整的视屏文件生成缩略图所至。看了下这个进程在打开的文件，果然就是fakeThunder正在下载的那个。
这可能也算quicklook本生的一个bug，我重启后再进行相同的操作这个进程出现了，但没有再占用那么高的CPU。
但还是建议fakeThunder为没下载完的文件添加一个后缀避免触发这个进程。

**Comment by eric5845191** [comment]
the same issue

**Comment by AlexRezit** [comment]
那样的话边下边看就不方便了.

**Comment by ruizzz** [comment]
fakeThunder哪有边下边看的功能？fakeThunder一边下载着你一边播放那临时文件吗？

**Comment by AlexRezit** [comment]
对啊, 直接播放临时文件.

**Comment by ruizzz** [comment]
……好吧，我从没用过这个功能，我也不愿为了这个功能牺牲我100%的CPU

**Comment by AlexRezit** [comment]
我就从来没遇到过这个问题的说...

**Comment by ruizzz** [comment]
你大概没下载过.mp4或者.m4v的文件

**Comment by AlexRezit** [comment]
我知道 MP4 不行. 反正我也不看. 高清格式大多都是 mkv 的, 表示毫无压力~
