### ISSUE TITLE
mplayerX下架之后从官方dmg安装，不能云点播

### ISSUE THREAD

**Issue by 29x10** [MartianZ/fakeThunder#49]
mplayerX因为沙箱问题从app store下架之后从http://mplayerx.org下载安装

fakeThunder不能云点播

**Comment by FedHoo** [comment]
同样的问题。回到App Store下载，还是不行。不知道是不是Thunder的问题不。

**Comment by AlexRezit** [comment]
不是 MPlayerX 的问题, 是迅雷 API 的问题. 

{
    "error_msg" = "please read vod_permit";
    ret = 11;
    userid = ********;
    "vod_permit" =     {
        msg = "overdue session";
        ret = 4;
    };
}

**Comment by 29x10** [comment]
jsonp1234567890({"resp": {"vod_permit": {"msg": "overdue session", "ret": 4}, "userid": "***********", "error_msg": "please read vod_permit", "ret": 11}})

**Comment by FedHoo** [comment]
请问一下  你给的代码怎么用？

**Comment by panxin299** [comment]
同样的问题，神给解决一下吧，否则只能下载完了才能看，折磨人啊

**Comment by hkkk** [comment]
现在不能关联mplayx播放云播放了，能帮忙解决一下么？

**Comment by 66beta** [comment]
me too，虽然平时习惯下载完了看，但是想云点播的时候不能看，很纠结，很难受

**Comment by AlexRezit** [comment]
Binux 已经给出 fix 了, 作者更新之前自己 compile 一个就好了.
