### ISSUE TITLE
fakethunder暂停之后的BT任务无法继续。

### ISSUE THREAD

**Issue by lucianzhu** [MartianZ/fakeThunder#55]
今天有一个BT的下载任务，下载一半之后我手动点了暂停，然后就合上笔记本的盖子休眠了。再打开盖子想继续任务的时候，发现没有可用的按钮来继续下载…

**Comment by AlexRezit** [comment]
正常... 看源码就会发现作者其实挺偷懒的... 判断任务状态直接根据 Label 来的. XD
