### ISSUE TITLE
下载时有大量的上传，会造成网络阻塞

### ISSUE THREAD

**Issue by lersh** [MartianZ/fakeThunder#56]
我的网络限速512k上传，fakethunder下载时，上传带宽被沾满了，造成无法打开网页等其他网络操作

**Comment by miniers** [comment]
木有可能...内置下载核心可是aria2..这玩意..可不是迅雷..你想多了..肯定是别的软件..

**Comment by lersh** [comment]
楼上的你用活动监视器，或者路由器本身的流量监控看看就知道了，只要开fakethunder下载，必然有50k以上的上传，因为我的线路是上传限速512K，所以不知道是否能达到更多的上传，但是一关掉fakethunder，上传立刻就没有了

**Comment by AlexRezit** [comment]
我上传的带宽极限是 500KB/s, 开 fakeThunder 之后最多也就 20KB/s, 而且都不确定是不是 ft 占的带宽.
aria2c 可不是迅雷啥的, 你们想多了.

**Comment by ruizzz** [comment]
http下载哪来的上传……
