### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by bennya8** [MartianZ/fakeThunder#59]
fakeThunder: Version 1.0 (10)
OS: 10.8.2 (12C53)
Error code:
登录失败，请检查您的用户名和密码！并确保当前的fakeThunder为最新版本。如果仍然无法正常登录，请到官方网站发送反馈。

**Comment by binux** [comment]
我测试没有问题，你密码有特殊字符吗？使用uid还是什么方式登陆？
