### ISSUE TITLE
怎么还没回复。。。

### ISSUE THREAD

**Issue by fantasyx** [MartianZ/fakeThunder#60]
等了很多天了，捐款白捐了，作者support 太慢了。。。

**Comment by binux** [comment]
作者开学读书去了，没有电脑。

**Comment by fantasyx** [comment]
你是老友？ 所以什么时候能解决呢，不方便啊不方便。。。 不是开源的么，没人改改么。。哎

**Comment by ruizzz** [comment]
既然是开源的，作者只是接受捐款，也没义务提供支持吧

**Comment by AlexRezit** [comment]
登录之类的问题一般都是迅雷那边再乱搞, 跟 fakeThunder 没什么关系的.

**Comment by binux** [comment]
我试了，功能上没有问题啊

**Comment by AlexRezit** [comment]
@binux 你的 API 里面云点播的那个不能用了... 迅雷貌似限制了 referer...

**Comment by fantasyx** [comment]
无法登陆。。。 云播放也就算乐，下载功能还是需要的。。。
