### ISSUE TITLE
下载AVI等视频文件的时候会导致QTKitServer进程占用CPU过高

### ISSUE THREAD

**Issue by micturkey** [MartianZ/fakeThunder#62]
我查了一下 是因为fakethunder在下载的时候不更改后缀造成的
而QTKitServer进程是系统的缩略图进程,而该文件一直在更新,所以它就会一直占着内存
解决方法有两条
一条就是在离线空间把AVI改成其他的后缀 比如AAA
另外一条就是fakethunder在下载的时候可以把后缀改成类似.download的格式了
希望下一个版本能解决这个问题

**Comment by AlexRezit** [comment]
= = 这个你可以直接改源码... 咱一直下 mkv 的表示不改后缀就可以边下边看很方便.

**Comment by micturkey** [comment]
@AlexRezit  单单xcode就把我折腾的蛋疼..而且我根本不会obj-c= = c也只会解解计算题,api根本不会使T_T...用avi主要是因为我想下完以后直接放到移动硬盘接到电视上看,sony的电视不支持mkv...

**Comment by ruizzz** [comment]
这个问题我也报过一次了
