### ISSUE TITLE
如何登入？

### ISSUE THREAD

**Issue by TingKarHui** [MartianZ/fakeThunder#63]
登录失败，请检查您的用户名和密码！并确保当前的fakeThunder为最新版本。如果仍然无法正常登录，请到官方网站发送反馈。

什么问题 ？请问是使用在迅雷官网上注册的帐号吗 ？一直都登入不了 ＝＝

**Comment by poplarch** [comment]
最近也出现突然无法登录的情况，不过有时候又可以登录。

**Comment by Mingyi** [comment]
同样出现这样的问题。

**Comment by poplarch** [comment]
清理一下safari的cookies，还是有一定几率可以登录的。

**Comment by ruizzz** [comment]
这登陆问题是要开多少个issue啊，这又不是论坛
