### ISSUE TITLE
有些视频无法使用云播放

### ISSUE THREAD

**Issue by littleben** [MartianZ/fakeThunder#7]
已经去掉了ffmgeg的勾选。
播放某些视频的时候弹出："对不起，似乎mplayer在播放媒体前退出了”
而该视频在迅雷离线播放正常。

视频地址：ed2k://|file|绝命毒师.Breaking.Bad.S03E06.Chi_Eng.HR-HDTV.AC3.1024X576.x264-YYeTs人人影视.mkv|492496252|6E312C18ACC58B33A15CEAA13B69BCA4|h=E6XQ434DZ2HG5KZD3U42I6F32CWLBCFG|/
fakethunder：1.0（3）
mplayerx:1.0.14 (1527)
OS：10.8 GM

**Comment by MartianZ** [comment]
经过测试，这个视频文件在获得播放地址后，连接迅雷返回的HTTP状态码竟然是 

2012-07-25 12:58:18 ERROR 410: Gone.

不知道是什么原因引起，我会继续测试的，感谢您的反馈。

**Comment by mhb0925** [comment]
似乎现在云点播还不能拖动进度条，跳播？

**Comment by MartianZ** [comment]
实现很完善的跳播的话需要用他那个flash播放器或者自己再调整处理流…

不是很好解决啊，如果需要很频繁的快进的话还是推荐直接去离线网页

**Comment by mhb0925** [comment]
嗯。了解了。其实就是想确认下这个事。怕是我这边网络问题导致的。流这东西确实比较难搞。。没想到作者回复这么及时。加油。我如果想到什么好的需要加上的随时反馈给你。加油！

**Comment by MartianZ** [comment]
谢谢理解和支持=。=
