### ISSUE TITLE
无法登陆迅雷帐号

### ISSUE THREAD

**Issue by alvinhu** [MartianZ/fakeThunder#75]
确定用户名和密码没错。
迅雷VIP白金年费会员。我在lixian.xunlei.com登陆的时候需要输入验证码，是不是这个原因？

**Comment by binux** [comment]
有验证码确实是，现在还不能处理验证码

**Comment by alvinhu** [comment]
那就是说现在无法登录咯。。。

**Comment by xiaosong** [comment]
木有验证码，还是无法登录

**Comment by alvinhu** [comment]
浏览器登录 lixian.xunlei.com 需要验证码
在 fakeThunder 里登录不需要验证码，输入用户名密码提示登录失败，使用的是最新版本

**Comment by fengerzh** [comment]
我一开始也是这个现象，等很久之后说登录失败，但反复多试了几次后，居然可以成功登录了，楼上各位可以多试试。

**Comment by eassylo** [comment]
遇到同样的问题，110版本可以登陆，最新版无法登陆！

**Comment by kiddkai** [comment]
要多试几次才可以了
