### ISSUE TITLE
无法登陆。。。蛋疼

### ISSUE THREAD

**Issue by gnrm** [MartianZ/fakeThunder#79]
今天下午开机后发现刷不出列表，然后重新登陆就登不上了，可以确定账户密码是没问题的，因为网页上都能登陆，但是fakethunder上就死活登不上去。不知道有没有什么办法能够解决。。。

**Comment by lvnantony** [comment]
同样的问题

**Comment by ltt001** [comment]
一直这样 特别烦

**Comment by aaronbu** [comment]
額 註銷後登錄不能。。。

**Comment by Rtony** [comment]
不能登录

**Comment by fengyie007** [comment]
我也是的. 我在网页上登录时,需要输验证码. 不知道是不是这个原因? 这个登录不支持输入验证码.

**Comment by binux** [comment]
1、更新api
2、`xunlei._get_verifycode(username)` 如果返回为None，则需要验证码
3、`xunlei.verifycode()` 返回jpg格式验证码内容，可重复获取
4、调用`xunlei.login(username, password, verifycode)` 登陆

**Comment by MartianZ** [comment]
@binux 无奈了，迅雷又搞这个验证码了，我要赶工加上这个了……

最近忙得要死啊……╮(╯▽╰)╭

**Comment by sungisliu** [comment]
加油！

**Comment by watson2006** [comment]
加油！

**Comment by gnrm** [comment]
呃，我的恢复了，感谢！

**Comment by watson2006** [comment]
我的还没

**Comment by kimxiaoxiao** [comment]
登陆不了好烦。看不懂好烦。

**Comment by laojin6009** [comment]
老大辛苦一下，我们的幸福就靠你了

**Comment by kimxiaoxiao** [comment]
1、更新api
2、xunlei._get_verifycode(username) 如果返回为None，则需要验证码
3、xunlei.verifycode() 返回jpg格式验证码内容，可重复获取
4、调用xunlei.login(username, password, verifycode) 登陆

这一串是个啥意思啊？程序菜鸟求指教啊！

**Comment by ash0080** [comment]
所以能不能重新放个110   先用用?

**Comment by nowlily** [comment]
可以登陆了然后又不能登陆了。哭死

**Comment by lsnakel** [comment]
饿 完全不懂代码啊 大哥

**Comment by teresa123** [comment]
我也是同样的问题～～一直刷新不出列表，以为需要清空下缓存～～结果发现就登陆不上去了～～
那个代码之类的完全不懂啊～～该怎么解决>_<

**Comment by sungisliu** [comment]
ok了！感谢大大！

**Comment by teresa123** [comment]
问题解决了～～感谢大大～～
