### ISSUE TITLE
希望支持Retina MacBook Pro

### ISSUE THREAD

**Issue by lexrus** [MartianZ/fakeThunder#8]
除了app icon，其它图都很模糊，需要@2x的版本。

没开始下载时没必要显示进度条。

能上传BT种子吗？

**Comment by MartianZ** [comment]
谢谢您的建议，@2x我会开始制作的。

BT种子当前版本暂时不支持，您可以暂时使用 http://www.bt2magnet.com/ 这个服务来代替。后续版本会支持BT种子上传
