### ISSUE TITLE
间歇性出现暂停下载后无法恢复的问题

### ISSUE THREAD

**Issue by brickyang** [MartianZ/fakeThunder#93]
点击暂停后，出现的“暂停中……”按钮是灰色的，不能再点击，也无法恢复下载，必须关闭软件重开

所谓间歇性即不是每次都出现这个问题，但频率很高

![ ](https://f.cloud.github.com/assets/3139237/143288/b75a04a8-738f-11e2-8eaa-33aa6224e7b7.jpg)

**Comment by sevear** [comment]
我几乎每次都会碰到……
