### ISSUE TITLE
下载目录不明确

### ISSUE THREAD

**Issue by Jreen** [MartianZ/fakeThunder#98]
我在很多文件夹找了半天没找到
最后用搜索引擎发现某个文件，我就双击（仍没在当前目录显示我下载的东西）
建议支持可选择的下载目录。

**Comment by shiniv** [comment]
一看就知道你没打开过程序的偏好设置。。
在常规标签页中---将新添加的下载认为储存在---选择你要下载的目录 
然就就好了

**Comment by Jreen** [comment]
我的确是osx新人 一直不太习惯。。正在熟悉 
谢谢你了

**Comment by iveney** [comment]
但是这个的确是功能上的一个缺陷，我建议：
1. 提供选项，可以选择下载到默认目录，或者每次下载前询问。大多数app都这么干的。
2. 提供已完成任务列表，或者打开已下载项目所在folder

迟点有时间会做一个 pull request……
